pipeline:

  linux-packer-validate:
    image: quay.io/ukhomeofficedigital/dq-packer-ansible
    commands:
      - export HOME=/home/packer
      - packer validate packer.json

  inspect:
    image: quay.io/ukhomeofficedigital/dq-packer-ansible
    commands:
      - export HOME=/home/packer
      - packer inspect packer.json

  build:
    image: quay.io/ukhomeofficedigital/dq-packer-ansible
    commands:
      - export HOME=/home/packer
      - export DRONE_BUILD_NUMBER=$${DRONE_BUILD_NUMBER}
      - packer build packer.json
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    when:
      event: push
